version: '3.4'

services:
  codebelt.website:
    image: ${DOCKER_REGISTRY-}codebeltwebsite
    build:
      context: src/Codebelt.Website/.
      dockerfile: Dockerfile
  codebelt.static:
    image: codebeltnet/web-cdn-origin:1.1.5
    ports:
      - "8000:80"
    volumes:
      - ./src/Codebelt.Website/cdnroot:/cdnroot